url: 'https://totaltailwheel.com'
baseurl: '/72c'
title: 'Total Tailwheel, LLC'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
