url: 'https://seven2charlie.com'
baseurl: ''
title: 'Total Tailwheel'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
